# Generated by Django 5.0.3 on 2024-03-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('task_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='category.addcategory')),
            ],
        ),
    ]
