# Generated by Django 5.0.3 on 2024-03-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='Rana', max_length=20),
        ),
    ]
